        ; enable graphics mode setting
        mov     dx,0x3bf
        mov     al,3
        out     dx,al
        ; initialize controller
        mov     dx,0x3b4
        mov     al,0
        out     dx,al
        inc     dx
        mov     al,0x35
        out     dx,al
        dec     dx
        mov     al,1
        out     dx,al
        inc     dx
        mov     al,0x2d
        out     dx,al
        dec     dx
        mov     al,2
        out     dx,al
        inc     dx
        mov     al,0x2e
        out     dx,al
        dec     dx
        mov     al,3
        out     dx,al
        inc     dx
        mov     al,0x07
        out     dx,al
        dec     dx
        mov     al,4
        out     dx,al
        inc     dx
        mov     al,0x5b
        out     dx,al
        dec     dx
        mov     al,5
        out     dx,al
        inc     dx
        mov     al,0x02
        out     dx,al
        dec     dx
        mov     al,6
        out     dx,al
        inc     dx
        mov     al,0x57
        out     dx,al
        dec     dx
        mov     al,7
        out     dx,al
        inc     dx
        mov     al,0x57
        out     dx,al
        dec     dx
        mov     al,8
        out     dx,al
        inc     dx
        mov     al,0x02
        out     dx,al
        dec     dx
        mov     al,9
        out     dx,al
        inc     dx
        mov     al,0x03
        out     dx,al
        dec     dx
        mov     al,10
        out     dx,al
        inc     dx
        mov     al,0x00
        out     dx,al
        dec     dx
        mov     al,11
        out     dx,al
        inc     dx
        mov     al,0x00
        out     dx,al
        ; set graphics mode
        mov     dx,0x3b8
        mov     al,2
        out     dx,al
        ; draw screen
        mov     ax,0xb000
        push    ax
        pop     es
        mov     di,0
        mov     al,0xaa
        mov     cx,0x4000
        rep stosb
        mov     di,0x4000
        mov     al,0x55
        mov     cx,0x4000
        rep stosb
